### PR TITLE
Move content to README so it is visible on repo homepage

### PR DESCRIPTION
**Pull request by sklarsa**
Currently, when you first load the repo, the content is the license. I think we should move the main content to README.md (at least for now), so we have a more welcoming experience for newcomers

image

### CODE REVIEW

**Review by jbattiato — APPROVED** [review]

**Comment by sklarsa** [comment]
@Paul-TT I would merge this after everyone's PRs to avoid conflicts

**Comment by Paul-TT** [comment]
@sklarsa  Makes sense. Thanks, Steve.

**Comment by jbattiato** [comment]
@sklarsa could you please update your branch and resolve conflicts? I don't have write access to this.
Then, @Paul-TT , I think we can merge this.

**Comment by sklarsa** [comment]
@jbattiato github auto-closed this PR.. will just re-open this one from a non-main branch in my fork to make things easier

**Pull request closed without merging**
